### PR TITLE
Update dependencies, and fix warnings

### PR DESCRIPTION
**Pull request by linkmauve**
This also removes the default features on glfw, these can be enabled by a user of this library down the road if they need them.

### CODE REVIEW

**Comment by phaazon** [comment]
Thanks a lot! ♥

**Comment by phaazon** [comment]
Hm, [though](https://travis-ci.org/phaazon/luminance-rs/jobs/565591878#L764):

```
/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-0.30.0/src/lib.rs:951: undefined reference to `glfwWindowHintString'
          /home/travis/build/phaazon/luminance-rs/target/debug/deps/libglfw-001c470128b28c3f.rlib(glfw-001c470128b28c3f.glfw.akx66uv4-cgu.0.rcgu.o): In function `glfw::Window::set_maximize_polling::h685fb8a6181eec04':
          /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-0.30.0/src/lib.rs:2234: undefined reference to `glfwSetWindowMaximizeCallback'
          /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-0.30.0/src/lib.rs:2234: undefined reference to `glfwSetWindowMaximizeCallback'
          /home/travis/build/phaazon/luminance-rs/target/debug/deps/libglfw-001c470128b28c3f.rlib(glfw-001c470128b28c3f.glfw.akx66uv4-cgu.0.rcgu.o): In function `glfw::Window::set_content_scale_polling::h2ad5d9371644001d':
          /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-0.30.0/src/lib.rs:2239: undefined reference to `glfwSetWindowContentScaleCallback'
          /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-0.30.0/src/lib.rs:2239: undefined reference to `glfwSetWindowContentScaleCallback'
          collect2: error: ld returned 1 exit status
```

**Comment by linkmauve** [comment]
Hmm, looks like the GLFW version available on your CI is too old for this version of glfw-rs.

**Comment by phaazon** [comment]
Thanks again!

**Pull request merged**
