### PR TITLE
Return TextureError::UnsupportedPixelFormat if the WebGL Pixel Format does not exist. #364

### PR DESCRIPTION
**Pull request by austinjones**
Hey @phaazon!
How's it going?  Here is a PR for #364

### CODE REVIEW

**Comment by austinjones** [comment]
Also, I was looking at your WebGL commits - super cool.  I'm working on a WASM/WebGL app with a Rust backend and definitely will use it when it's ready!  I was tried to hack it with `luminance-webgl = { git =  "https://github.com/phaazon/luminance-rs.git"  }`, but it depends on 0.40.  Is there any way to use it before you publish 0.40?

**Comment by phaazon** [comment]
Woah, you have a WebGL app backed by luminance working? Amazing! <3

**Comment by austinjones** [comment]
Yep, I just got the hello-triangles rendering!  I cherry-picked #380, and changed the webgl2 GLSL_PRAGMA const to `#version 300 es`.  Works like a charm.

triangles

**Pull request merged**
